Repository GSG-FC02/Quotes-Generator, pull requests merged in 2021-03, with the labels that each got.

#6 Create files stucture
  index.html
  script.js
  style.css
Labels: Done, awaiting-review

#8 Create Style file
  style.css
Labels: Done

#9 Create Read me file
  README.md
Labels: awaiting-review

#11 create script file and add some stayles
  script.js
  style.css
Labels: awaiting-review
